version: '3.8'
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eventapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=eventapi_db
      - DB_USER=user
      - DB_PASSWORD=password

volumes:
  db_data:
